extends: '@textshq/eslint-config/base.yml'
parserOptions:
  project: ./tsconfig.eslint.json
rules:
  'class-methods-use-this': 0
plugins:
  - jest
overrides:
  - files: "tests/*.js"
    env:
      "jest/globals": true
